# Generated by Django 6.0.1 on 2026-01-27 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Order in the learning path')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='time_taken',
            field=models.IntegerField(help_text='Time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assessment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='topic_strength',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='coding_app.topic'),
        ),
    ]
